version: '3.8'
services:
  smarthouse-controller:
    image: 'smarthouse-controller:latest'
    build:
      context: .
    container_name: smarthouse-controller
    depends_on:
      - smarthouse-db
      - smarthouse-mqtt-broker
    ports:
      - '24867:24867'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://smarthouse-db:5432/smarthouse
      - SPRING_DATASOURCE_USERNAME=smarthouse
      - SPRING_DATASOURCE_PASSWORD=smarthouse
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped

  smarthouse-db:
    image: postgres:14.5
    container_name: smarthouse-db
    environment:
      - POSTGRES_USER=smarthouse
      - POSTGRES_PASSWORD=smarthouse
    ports:
      - '24870:5432'
    volumes:
      #      - /home/akuzko/IdeaProjects/smarthouse-controller/db/smarthouse.sql:/docker-entrypoint-initdb.d/smarthouse.sql # restore db from local dump
      - /home/alexkzk/smarthouse/docker/postgresql:/var/lib/postgresql/data
    restart: unless-stopped

  smarthouse-mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: smarthouse-mqtt-broker
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # Websockets (optional)
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

volumes:
  db:
    driver: local
