version: '3.8'
services:
  smarthouse-controller:
    image: 'smarthouse-controller:latest'
    build:
      context: .
    container_name: smarthouse-controller
    depends_on:
      - smarthouse-db
      - smarthouse-mqtt-broker
      - influxdb
    ports:
      - '24867:24867'
    environment:
      - JAVA_OPTS=-XX:-UseContainerSupport
      - SPRING_DATASOURCE_URL=jdbc:postgresql://smarthouse-db:5432/smarthouse
      - SPRING_DATASOURCE_USERNAME=smarthouse
      - SPRING_DATASOURCE_PASSWORD=smarthouse
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped

  smarthouse-db:
    image: postgres:14.5
    container_name: smarthouse-db
    environment:
      - POSTGRES_USER=smarthouse
      - POSTGRES_PASSWORD=smarthouse
    ports:
      - '24870:5432'
    volumes:
      # Database data directory
      - /home/alexkzk/smarthouse/docker/postgresql:/var/lib/postgresql/data
    restart: unless-stopped

  smarthouse-mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: smarthouse-mqtt-broker
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # Websockets (optional)
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"  # InfluxDB HTTP API
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=Home
      - DOCKER_INFLUXDB_INIT_BUCKET=935-CORKWOOD
      - DOCKER_INFLUXDB_INIT_RETENTION=7d  # Optional data retention period
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=smarthouse_token
    volumes:
      - /home/alexkzk/influxdb_data:/var/lib/influxdb2

    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
      - smarthouse-mqtt-broker
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    restart: unless-stopped

volumes:
  db:
    driver: local
  influxdb_data:
    driver: local
