services:
  smarthouse-controller:
    image: 'smarthouse-controller:latest'
    build:
      context: .
    container_name: smarthouse-controller
    depends_on:
      - smarthouse-db
      - smarthouse-influxdb
      - smarthouse-mqtt-broker
    ports:
      - '24867:24867'
    environment:
      - JAVA_OPTS=-XX:-UseContainerSupport
      - SPRING_DATASOURCE_URL=jdbc:postgresql://smarthouse-db:5432/smarthouse
      - SPRING_DATASOURCE_USERNAME=smarthouse
      - SPRING_DATASOURCE_PASSWORD=smarthouse
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped
    networks:
      - smarthouse_network

  smarthouse-db:
    image: postgres:14.5
    container_name: smarthouse-db
    environment:
      - POSTGRES_USER=smarthouse
      - POSTGRES_PASSWORD=smarthouse
    ports:
      - '24870:5432'
    volumes:
      # Database data directory
      - /home/alexkzk/smarthouse/docker/postgresql:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - smarthouse_network

  smarthouse-influxdb:
    image: influxdb:2.0
    container_name: smarthouse-influxdb
    ports:
      - "8086:8086" # InfluxDB HTTP API
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup                           # Setup mode
      - INFLUXDB_ADMIN_TOKEN=asdf==
    volumes:
      - /home/alexkzk/influxdb_data:/var/lib/influxdb2            # Persistent storage
    restart: unless-stopped
    networks:
      - smarthouse_network

  smarthouse-mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: smarthouse-mqtt-broker
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # Websockets (optional)
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped
    networks:
      - smarthouse_network

networks:
  smarthouse_network:
    external: true
