spring:
  datasource:
    url: jdbc:postgresql://192.168.0.201:24870/smarthouse

logging:
  filepath: ./log
  level:
    org:
      hibernate:
        SQL: debug

mqtt:
  server: 192.168.0.201
  msgSavingEnabled: false
