spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smarthouse
    username: smarthouse
    password: ${SMARTHOUSE_POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
logging:
  filepath: ./log
  level:
    org:
      hibernate:
        SQL: debug
#    com.alexsoft.smarthouse: trace
server:
  port: 24867

mqtt:
  server: 127.0.0.1
  port: 1883
  msgSavingEnabled: true