spring:

  datasource:
    url: jdbc:postgresql://localhost:24870/smarthouse
    driver-class-name: org.postgresql.Driver
    username: smarthouse
    password: smarthouse

mqtt:
  msgSavingEnabled: false
  server: 192.168.0.201

  # UNCOMMENT TO LOG HIBERNATE DB REQUESTS
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql: trace
#    org.hibernate.orm.jdbc.bind: trace

