server:
  port: 24867
  servlet:
    context-path: /smarthouse

spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: smarthouse
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:postgresql://${smarthouse.db.hostname}:${smarthouse.db.port}/${smarthouse.db.name}
    driver-class-name: org.postgresql.Driver
    username: smarthouse
    password: smarthouse

logging:
  filepath: .
  main:
    name: smarthouse
    max-history: 90
  msg:
    name: smarthouse-msg
    max-history: 3
  sql:
    name: smarthouse-sql
    max-history: 1
  level:
    root: info
    com.alexsoft.smarthouse: debug

mqtt:
  server: smarthouse-mqtt-broker
  port: 1883
  topic: mqtt.smarthouse
  subscriber: alex-ws-ubuntu
#  user: alexkzk  # currently not used
#  password: ${MOSQUITTO_PASSWORD}  # currently not used
  msgSavingEnabled: true
  msgSendingEnabled: true

avwx:
  baseUri: https://avwx.rest/api
  metarSubUri: /metar/{ICAO}?options=&airport=true&reporting=true&format=json&onfail=cache
  token: W2pxukczIQFQ4cFZDbRcHpwleKO76osWaQ5LsngVlDo
  metar-receiving-cron: 0 */30 * * * *

flightradar24:
  baseUri: https://fr24api.flightradar24.com
  token: ${FLIGHTRADAR24_TOKEN}
  aircraft-reading-cron: "0 */3 * * * *"
time:
  local-time-zone: America/New_York
  chart-date-time-pattern: E d, HH:mm

smarthouse:
  db:
    port: 5436
    name: smarthouse
    hostname: localhost
    filename: smarthouse-dbdump.sql
    dump-on-destroy: true
    restore-on-startup: false
  ftp:
    hostname: 192.168.0.1
    username: anonymous
    password: ${smarthouse.ftp.username}@${smarthouse.ftp.hostname}
    remote-path: /G/backup/smarthouse
    upload-on-destroy: ${smarthouse.db.dump-on-destroy}
  colors:
    MIAMI: '#0BB0FF'

  short-status-null-string: N

metar-locations:
  location-mapping:
    MONTGOMERY:
      KMGM: America/Chicago
    ANCHORAGE:
      PANC: America/Anchorage
    PHOENIX:
      KPHX: America/Denver
    LITTLE-ROCK:
      KLIT: America/Chicago
    PHILADELPHIA:
      KPHL: America/New_York
    MINEAPOLIS:
      KMSP: America/Chicago
    BISMARK:
      KBIS: America/Chicago
    PORTLAND:
      KPDX: America/Los_Angeles
    AUGUSTA:
      KAGS: America/New_York
    INDIANAPOLIS:
      KIND: America/New_York
    SEATTLE:
      KSEA: America/Los_Angeles
    SAN-FRANCISCO:
      KSFO: America/Los_Angeles
    MIAMI:
      KMIA: America/New_York
    FORT-LAUDERDALE:
      KFLL: America/New_York
    ORLANDO:
      KMCO: America/New_York
    BOISE:
      KBOI: America/Denver
    CHEYENNE:
      KCYS: America/Denver
    ATLANTA:
      KATL: America/New_York
    BOSTON:
      KBOS: America/New_York
    CHICAGO:
      KORD: America/Chicago
    LOS-ANGELES:
      KLAX: America/Los_Angeles
    SUCEAVA:
      LRSV: Europe/Bucharest
    TORONTO:
      CYYZ: Canada/Eastern
    AUSTIN:
      KAUS: America/Chicago
    BOLZANO:
      LIPB: Europe/Rome
    DENVER:
      KDEN: America/Denver
    NAPOLI:
      LIRN: Europe/Rome
    CLEAVELAND:
      KCLE: America/New_York
    HELENA:
      KHLN: America/Denver
    SALT-LAKE-CITY:
      KSLC: America/Denver
    DESTIN:
      KVPS: America/New_York
    JACKSONVILLE:
      KJAX: America/New_York
