server:
  servlet:
    context-path: /smarthouse

spring:
  application:
    name: smarthouse
  #  liquibase:
  #    liquibase-schema: liquibase
  #    change-log: classpath:db/changelog.xml
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    url: jdbc:postgresql://185.212.128.246:5432/smarthouse
    driver-class-name: org.postgresql.Driver
    username: guessword
    password: guessword<G13

logging:
  file:
    enabled: true
    path: /var/log/smarthouse
    file-name: smarthouse
    max-history: 90
  level:
    root: info
    com.alexsoft.smarthouse: debug

mqtt:
  server: 185.212.128.246
  port: 1883
  topic: ALEXKZK-SMARTHOUSE
  subscriber: alex-ws-ubuntu
  user: alexkzk
  password: Vlena<G13

avwx:
  baseUri: https://avwx.rest/api
  metarSubUri: /metar/UKLN?options=&airport=true&reporting=true&format=json&onfail=cache
  token: W2pxukczIQFQ4cFZDbRcHpwleKO76osWaQ5LsngVlDo