server:
  servlet:
    context-path: /smarthouse

spring:
  application:
    name: smarthouse
#    liquibase: # todo temporary disabled until the database schema is finalized
#      liquibase-schema: liquibase
#      change-log: classpath:db/changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
  datasource:
    url: jdbc:postgresql://185.212.128.246:5432/smarthouse
    driver-class-name: org.postgresql.Driver
    username: guessword
    password: guessword<G13

logging:
  filepath: /var/log/smarthouse
  main:
    name: smarthouse
    max-history: 90
  msg:
    path: /var/log/smarthouse
    name: smarthouse-msg
    max-history: 3
  level:
    root: info
    com.alexsoft.smarthouse: debug

mqtt:
  server: 185.212.128.246
  port: 1883
  topic: ALEXKZK-SMARTHOUSE
  subscriber: alex-ws-ubuntu
  user: alexkzk
  password: Vlena<G13
  msgSavingEnabled: true

avwx:
  baseUri: https://avwx.rest/api
  metarSubUri: /metar/UKLN?options=&airport=true&reporting=true&format=json&onfail=cache
  token: W2pxukczIQFQ4cFZDbRcHpwleKO76osWaQ5LsngVlDo