server:
  servlet:
    context-path: /smarthouse

spring:
  application:
    name: smarthouse
#    liquibase: # todo temporary disabled until the database schema is finalized
#      liquibase-schema: liquibase
#      change-log: classpath:db/changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
  datasource:
    url: jdbc:postgresql://192.168.1.100:5432/smarthouse
    driver-class-name: org.postgresql.Driver
    username: smarthouse

logging:
  filepath: /var/log/smarthouse
  main:
    name: smarthouse
    max-history: 90
  msg:
    name: smarthouse-msg
    max-history: 3
  sql:
    name: smarthouse-sql
    max-history: 1
  level:
    root: info
    com.alexsoft.smarthouse: debug

sensor:
  bme680-temp-adjustment: 0

mqtt:
  server: 192.168.1.100
  port: 1883
  topic: ALEXKZK-SMARTHOUSE
  subscriber: alex-ws-ubuntu
  user: alexkzk
  password: Vlena<G13
  msgSavingEnabled: true

avwx:
  baseUri: https://avwx.rest/api
  metarSubUri: /metar/{ICAO}?options=&airport=true&reporting=true&format=json&onfail=cache
  token: W2pxukczIQFQ4cFZDbRcHpwleKO76osWaQ5LsngVlDo
  chernivtsi-icao: UKLN
  seattle-icao: KSEA
  miami-icao: KMIA
  metar-receiving-cron: 0 */2 * * * *

time:
  local-time-zone: Europe/Kiev
  chart-date-time-pattern: E d, HH:mm