server:
  port: 24867
  servlet:
    context-path: /smarthouse

spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: smarthouse
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/smarthouse
    driver-class-name: org.postgresql.Driver
    username: smarthouse
    password: ${SMARTHOUSE_POSTGRES_PASSWORD}

logging:
  filepath: /var/log/smarthouse
  main:
    name: smarthouse
    max-history: 90
  msg:
    name: smarthouse-msg
    max-history: 3
  sql:
    name: smarthouse-sql
    max-history: 1
  level:
    root: info
    com.alexsoft.smarthouse: debug

mqtt:
  server: localhost
  port: 8883
  topic: ALEXKZK-SMARTHOUSE
  subscriber: alex-ws-ubuntu
  user: alexkzk
  password: ${MOSQUITTO_PASSWORD}
  msgSavingEnabled: true

avwx:
  baseUri: https://avwx.rest/api
  metarSubUri: /metar/{ICAO}?options=&airport=true&reporting=true&format=json&onfail=cache
  token: W2pxukczIQFQ4cFZDbRcHpwleKO76osWaQ5LsngVlDo
  chernivtsi-icao: UKLN
  seattle-icao: KSEA
  miami-icao: KMIA
  metar-receiving-cron: 0 */30 * * * *

time:
  local-time-zone: America/New_York
  chart-date-time-pattern: E d, HH:mm

smarthouse:
  colors:
    MIAMI: '#00B0FF'
    UKLN: '#8d47b5'
    SEATTLE: '#109618'
    NORTH: '#3769cd'
    SOUTH: '#379bcd'
    NORTH2: grey
    LIVING-ROOM: '#dc3912'
    TERRACE: '#ff5959'

  short-status-null-string: N

metar-locations:
  location-mapping:
    SEATTLE:
      KSEA: America/Los_Angeles
    SAN-FRANCISCO:
      KSFO: America/Los_Angeles
    MIAMI:
      KMIA: America/New_York
    ATLANTA:
      KATL: America/New_York
    BOSTON:
      KBOS: America/New_York
    CHICAGO:
      KORD: America/Chicago
    LOS-ANGELES:
      KLAX: America/Los_Angeles
    SUCEAVA:
      LRSV: Europe/Bucharest
    TORONTO:
      CYYZ: Canada/Eastern
    AUSTIN:
      KAUS: America/Chicago
    BOLZANO:
      LIPB: Europe/Rome
    DENVER:
      KDEN: America/Denver