spring:
  datasource:
    url: jdbc:postgresql://localhost:15783/smarthouse
    username: smarthouse
    password: smarthouse
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
logging:
  filepath: ./log
  level:
    org:
      hibernate:
        SQL: debug
#    com.alexsoft.smarthouse: trace
server:
  port: 24867

mqtt:
  server: 134.249.167.33
  port: 1883
  msgSavingEnabled: true