mqtt:
  server: 134.249.167.33
  port: 1883

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://134.249.167.33:5432/smarthouse
    password: Vlena<H13
logging:
  level:
    org:
      hibernate:
        SQL: debug

#server:
#  ssl:
#    enabled: true
#    key-store: classpath:keystore/smarthouse.p12
#    key-store-type: PKCS12
#    key-store-password: Vlena<G13
#    key-alias: smarthouse